import joblib
import shap
import pandas as pd
import numpy as np

from backend.config import MODEL_PATH

DISCLAIMER = (
    "⚠️ This explanation is generated by an experimental AI prototype. "
    "It must not be used for medical diagnosis or treatment decisions."
)


def _load_model():
    return joblib.load(MODEL_PATH)


def _fallback_explanation(patient_data: dict):

    fallback = []

    for key, value in patient_data.items():

        if isinstance(value, (int, float)):

            fallback.append(
                {
                    "feature": key,
                    "value": float(value),
                    "importance": round(abs(float(value)), 2),
                }
            )

    fallback = sorted(
        fallback,
        key=lambda x: x["importance"],
        reverse=True,
    )[:5]

    text = (
        "The explainability engine is temporarily unavailable. "
        "The fallback explanation highlights the largest numerical factors."
    )

    return {
        "top_factors": fallback,
        "shap_values": {},
        "plain_english": text,
        "disclaimer": DISCLAIMER,
    }


def explain_prediction(patient_data: dict):

    try:

        model = _load_model()

        preprocessor = model.named_steps["preprocessor"]
        classifier = model.named_steps["classifier"]

        df = pd.DataFrame([patient_data])

        transformed = preprocessor.transform(df)

        explainer = shap.TreeExplainer(classifier)

        shap_values = explainer.shap_values(transformed)

        values = (
            shap_values[1][0]
            if isinstance(shap_values, list)
            else shap_values[0]
        )

        names = preprocessor.get_feature_names_out()

        explanation = []

        for feature, impact in zip(names, values):

            explanation.append(
                {
                    "feature": str(feature),
                    "importance": round(float(impact), 4),
                }
            )

        explanation = sorted(
            explanation,
            key=lambda x: abs(x["importance"]),
            reverse=True,
        )[:5]

        summary = (
            "The prediction was primarily influenced by "
            + ", ".join(
                item["feature"]
                for item in explanation[:3]
            )
            + "."
        )

        return {
            "top_factors": explanation,
            "shap_values": {
                item["feature"]: item["importance"]
                for item in explanation
            },
            "plain_english": summary,
            "disclaimer": DISCLAIMER,
        }

    except Exception:

        return _fallback_explanation(patient_data)